version: '3.8'

services:
  lms-checker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MOODLE_BASE_URL=${MOODLE_BASE_URL}
      - MOODLE_TOKEN=${MOODLE_TOKEN}
      - LINK_CHECKER_TIMEOUT=30